[package]
name = "sound-monitor-desktop"
version = "0.1.0"
edition = "2021"

[lib]
name = "sound_monitor_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sound-monitor = { path = ".." }
tauri = { version = "2", features = [] }
