[package]
name = "sound-monitor"
version = "0.2.0-alpha.2"
edition = "2021"
license = "GPL-3.0-or-later"

[workspace]
members = ["src-tauri"]
resolver = "2"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
serde = { version = "1", features = ["derive"] }
serialport = { version = "4", default-features = false }
